"""
Prometheus metrics for RAG system monitoring.
"""

import time
from typing import Optional
from contextlib import contextmanager

from prometheus_client import (
    Counter,
    Histogram,
    Gauge,
    Summary,
    start_http_server,
    REGISTRY,
)

from src.config import settings

# ==========================================
# Metrics Definitions
# ==========================================

# Request metrics
request_counter = Counter(
    "rag_requests_total",
    "Total number of RAG requests",
    ["endpoint", "status"],
)

request_duration = Histogram(
    "rag_request_duration_seconds",
    "Request duration in seconds",
    ["endpoint"],
    buckets=[0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 30.0, 60.0],
)

# Search metrics
search_duration = Histogram(
    "rag_search_duration_seconds",
    "Search duration in seconds",
    buckets=[0.01, 0.05, 0.1, 0.5, 1.0, 2.0],
)

search_results_count = Histogram(
    "rag_search_results_count",
    "Number of search results returned",
    buckets=[0, 1, 3, 5, 10, 20, 50],
)

# LLM metrics
llm_generation_duration = Histogram(
    "rag_llm_generation_duration_seconds",
    "LLM generation duration in seconds",
    ["model"],
    buckets=[1.0, 2.0, 5.0, 10.0, 30.0, 60.0, 120.0],
)

llm_tokens_generated = Counter(
    "rag_llm_tokens_generated_total",
    "Total number of tokens generated by LLM",
    ["model"],
)

llm_errors = Counter(
    "rag_llm_errors_total",
    "Total number of LLM errors",
    ["model", "error_type"],
)

# Cache metrics
cache_hits = Counter("rag_cache_hits_total", "Total cache hits")
cache_misses = Counter("rag_cache_misses_total", "Total cache misses")

# Pipeline metrics
pipeline_status = Gauge(
    "rag_pipeline_status",
    "Pipeline status (1=ready, 0=not ready)",
)

contexts_retrieved = Histogram(
    "rag_contexts_retrieved",
    "Number of contexts retrieved per request",
    buckets=[0, 1, 2, 3, 4, 5, 10],
)

# Vector store metrics
vector_store_points = Gauge(
    "rag_vector_store_points",
    "Number of points in vector store",
    ["collection"],
)

vector_store_latency = Histogram(
    "rag_vector_store_latency_seconds",
    "Vector store operation latency",
    ["operation"],
    buckets=[0.01, 0.05, 0.1, 0.5, 1.0],
)


class MetricsCollector:
    """Collector for RAG system metrics."""

    def __init__(self, port: int = 9091):
        self.port = port
        self._server_started = False
        self.logger = logging.getLogger(f"{__name__}.MetricsCollector")

    def start_server(self):
        """Start Prometheus metrics server."""
        if not self._server_started:
            try:
                start_http_server(self.port)
                self._server_started = True
                self.logger.info(f"✅ Metrics server started on port {self.port}")
            except Exception as e:
                self.logger.error(f"❌ Failed to start metrics server: {e}")

    @contextmanager
    def measure_request(self, endpoint: str):
        """Context manager for measuring request duration."""
        start = time.time()
        status = "success"
        try:
            yield
        except Exception:
            status = "error"
            raise
        finally:
            duration = time.time() - start
            request_duration.labels(endpoint=endpoint).observe(duration)
            request_counter.labels(endpoint=endpoint, status=status).inc()

    @contextmanager
    def measure_search(self):
        """Context manager for measuring search duration."""
        start = time.time()
        try:
            yield
        finally:
            search_duration.observe(time.time() - start)

    @contextmanager
    def measure_llm(self, model: str = "ollama"):
        """Context manager for measuring LLM generation."""
        start = time.time()
        try:
            yield
        except Exception as e:
            error_type = type(e).__name__
            llm_errors.labels(model=model, error_type=error_type).inc()
            raise
        finally:
            llm_generation_duration.labels(model=model).observe(time.time() - start)

    def record_cache(self, hit: bool):
        """Record cache hit or miss."""
        if hit:
            cache_hits.inc()
        else:
            cache_misses.inc()

    def record_search_results(self, count: int):
        """Record number of search results."""
        search_results_count.observe(count)

    def record_contexts(self, count: int):
        """Record number of contexts retrieved."""
        contexts_retrieved.observe(count)

    def record_tokens(self, tokens: int, model: str = "ollama"):
        """Record number of tokens generated."""
        llm_tokens_generated.labels(model=model).inc(tokens)

    def update_pipeline_status(self, ready: bool):
        """Update pipeline status."""
        pipeline_status.set(1 if ready else 0)

    def update_vector_store_points(self, count: int, collection: str = "enterprise_docs"):
        """Update vector store points count."""
        vector_store_points.labels(collection=collection).set(count)

    @contextmanager
    def measure_vector_store(self, operation: str):
        """Context manager for measuring vector store operations."""
        start = time.time()
        try:
            yield
        finally:
            vector_store_latency.labels(operation=operation).observe(time.time() - start)


# Global metrics collector
_metrics_collector: Optional[MetricsCollector] = None


def setup_metrics(port: int = 9091) -> MetricsCollector:
    """Setup and return metrics collector."""
    global _metrics_collector
    if _metrics_collector is None:
        _metrics_collector = MetricsCollector(port=port)
    return _metrics_collector


def get_metrics() -> Optional[MetricsCollector]:
    """Get the global metrics collector."""
    return _metrics_collector